### ISSUE TITLE
Epoch Run

### ISSUE THREAD

**Issue by ritchieng** [easonnie/multiNLI_encoder#2]
Hi, thanks for this repository. May I know how many epochs did you run for? I can't seem to replicate results for MLI as after the default 6 epoch it's hovering at 59% dev accuracy with default settings.

**Comment by easonnie** [comment]
@ritchieng 
It should converge roughly at 3rd epoch with at least 70% on MultiNLI.
It seems to me that 59% dev accuracy you got is the result of SNLI dev instead of MultiNLI. The script will print out SNLI dev result first then MultiNLI.
https://github.com/easonnie/multiNLI_encoder/blob/572d3525bf9d16f08a36727be2991798128a52ae/model/tested_model/stack_3bilstm_last_encoder.py#L189
https://github.com/easonnie/multiNLI_encoder/blob/572d3525bf9d16f08a36727be2991798128a52ae/model/tested_model/stack_3bilstm_last_encoder.py#L195

Btw, I recommend checking out the ResEncoder in https://github.com/easonnie/ResEncoder.

**Comment by ritchieng** [comment]
Thanks for clarifying however it seems that it’s printing the dev accuracy of 70% and grows to 80%+ over the epoch for SNLI but not for MNLI which hovers at 58% across the epoch. 

If you run the scripts you would immediately notice this via the print statements in your command line across epochs.

**Comment by easonnie** [comment]
@ritchieng 
Sorry, my mistakes.
Please set the argument `combined_set` to be `True`.
https://github.com/easonnie/multiNLI_encoder/blob/572d3525bf9d16f08a36727be2991798128a52ae/model/tested_model/stack_3bilstm_last_encoder.py#L96

Otherwise, it will only be trained on SNLI.
https://github.com/easonnie/multiNLI_encoder/blob/572d3525bf9d16f08a36727be2991798128a52ae/model/tested_model/stack_3bilstm_last_encoder.py#L148
Make sure that the train_iter is assigned at this line.

**Comment by ritchieng** [comment]
Thanks, how many epoch did you run for to achieve the results you got in your paper for MNLI?

**Comment by easonnie** [comment]
I forgot the exact number but it should be around 3 or 4 epoches.
